src/Entity/Campagne.php
<?php

namespace App\Entity;

use App\Repository\CampagneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CampagneRepository::class)
 */
class Campagne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Candidats::class, mappedBy="idCampagne")
     */
    private $candidats;

    public function __construct()
    {
        $this->candidats = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Candidats>
     */
    public function getCandidats(): Collection
    {
        return $this->candidats;
    }

    public function addCandidat(Candidats $candidat): self
    {
        if (!$this->candidats->contains($candidat)) {
            $this->candidats[] = $candidat;
            $candidat->setIdCampagne($this);
        }

        return $this;
    }

    public function removeCandidat(Candidats $candidat): self
    {
        if ($this->candidats->removeElement($candidat)) {
            // set the owning side to null (unless already changed)
            if ($candidat->getIdCampagne() === $this) {
                $candidat->setIdCampagne(null);
            }
        }

        return $this;
    }
}

src/Form/CampagneType.php
<?php

namespace App\Form;

use App\Entity\Campagne;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampagneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('libelle')
            ->add('date_debut')
            ->add('date_fin')
            ->add('type')
            ->add('description');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Campagne::class,
        ]);
    }
}

src/Controller/Vote/CampagneController.php
<?php

namespace App\Controller;

use App\Entity\Campagne;
use App\Form\Campagne1Type;
use App\Repository\CampagneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/campagne")
 */
class CampagneController extends AbstractController
{
    /**
     * @Route("/", name="app_campagne_index", methods={"GET"})
     */
    public function index(CampagneRepository $campagneRepository): Response
    {
        return $this->render('campagne/index.html.twig', [
            'campagnes' => $campagneRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_campagne_new", methods={"GET", "POST"})
     */
    public function new(Request $request, CampagneRepository $campagneRepository): Response
    {
        $campagne = new Campagne();
        $form = $this->createForm(Campagne1Type::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campagneRepository->add($campagne);
            return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('campagne/new.html.twig', [
            'campagne' => $campagne,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_campagne_show", methods={"GET"})
     */
    public function show(Campagne $campagne): Response
    {
        return $this->render('campagne/show.html.twig', [
            'campagne' => $campagne,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_campagne_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Campagne $campagne, CampagneRepository $campagneRepository): Response
    {
        $form = $this->createForm(Campagne1Type::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $campagneRepository->add($campagne);
            return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('campagne/edit.html.twig', [
            'campagne' => $campagne,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_campagne_delete", methods={"POST"})
     */
    public function delete(Request $request, Campagne $campagne, CampagneRepository $campagneRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campagne->getId(), $request->request->get('_token'))) {
            $campagneRepository->remove($campagne);
        }

        return $this->redirectToRoute('app_campagne_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/campagne/_delete_form.html.twig
<form method="post" action="{{ path('app_campagne_delete', {'id': campagne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campagne.id) }}">
	<button class="btn">Delete</button>
</form>

templates/campagne/_form.html.twig
{{ form_start(form) }}
<div class="row">
	<div
		class="col-2">{# {{ form_row(registrationForm.adresse) }} #}
	</div>
	<div class="col">
		{{ form_row(form.libelle) }}
	</div>
	<div class="col" id="date-picker-example" class="md-form md-outline input-with-post-icon datepicker" inline="true">
		{{ form_row(form.date_debut) }}

	</div>
	<div class="col">
		{{ form_row(form.date_fin) }}
	</div>
	<div
		class="col-2">{# {{ form_row(registrationForm.adresse) }} #}
	</div>
</div>
<div class="row">
	<div
		class="col-2">{# {{ form_row(registrationForm.adresse) }} #}
	</div>
	<div class="col">
		{{ form_row(form.type) }}
	</div>

	<div class="col">
		{{ form_row(form.description) }}
	</div>
	<div
		class="col-2">{# {{ form_row(registrationForm.adresse) }} #}
	</div>
</div>
<div class="col text-center ">
	<button class="btn btn-primary">{{ button_label|default('Enregistrer la nouvelle campagne') }}</button>
</div>
{{ form_end(form) }}

templates/campagne/edit.html.twig
{% extends 'base.html copy.twig' %}

{% block title %}Edit Campagne
{% endblock %}

{% block body %}
	<h1>Edit Campagne</h1>

	{{ include('campagne/_form.html.twig', {'button_label': 'Update'}) }}

	<a href="{{ path('app_campagne_index') }}">back to list</a>

	{{ include('campagne/_delete_form.html.twig') }}
{% endblock %}

templates/campagne/index.html.twig
{% extends 'base.html copy.twig' %}

{% block title %}Campagne index
{% endblock %}

{% block body %}
	<div id="wrapper">
		<div class="container-fluid">
			<a href="{{ path('app_campagne_new') }}" class="btn btn-primary mb-4 ">Nouveau Campagne</a>
			<div class="card shadow mb-4">
				<div class="card-header py-3"></div>
				<div class="card-body">
					<div class="table-responsive">
						<table class="table table-bordered" id="dataTable">
							<thead>
								<tr>

									<th>Libelle</th>
									<th>Date_debut</th>
									<th>Date_fin</th>

									<th>Description</th>

									<th>Plus de details</th>
									<th>Modifier</th>
									<th>Supprimer</th>
								</tr>
							</thead>
							<tbody>
								{% for campagne in campagnes %}
									<tr>

										<td>{{ campagne.libelle }}</td>
										<td>{{ campagne.dateDebut ? campagne.dateDebut|date('Y-m-d') : '' }}</td>
										<td>{{ campagne.dateFin ? campagne.dateFin|date('Y-m-d') : '' }}</td>

										<td>{{ campagne.description }}</td>
										<td>
											<a href="{{ path('app_campagne_show', {'id': campagne.id}) }}">show</a>
										</td>
										<td>
											<a href="{{ path('app_campagne_edit', {'id': campagne.id}) }}">edit</a>
										</td>
										<td>
											<a href="{{ path('app_campagne_edit', {'id': campagne.id}) }}">edit</a>
										</td>
									</tr>
								{% else %}
									<tr>
										<td colspan="7">no records found</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>{% endblock %}

templates/campagne/new.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		{# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
		{% block stylesheets %}
			<link href="{{ asset ('assets/admin/vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
			<link
			href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

			<!-- Custom styles for this template-->
			<link href=" {{ asset ('assets/admin/css/sb-admin-2.min.css')}}" rel="stylesheet">
			<style>
				.container-fluid {
					background: white;
				}
				.body {
					background: whitesmoke;
				}
			</style>

			<link
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
			<!-- Google Fonts -->
			<link
			href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet"/>
			<!-- MDB -->
			<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.css" rel="stylesheet"/>
		{% endblock %}


	</head>
	<body id="page-top">

		{% block body %}
			<nav
				class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

				<!-- Sidebar Toggle (Topbar) -->
				<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
					<i class="fa fa-bars"></i>
				</button>

				<!-- Topbar Search -->

				<form class="d-none d-sm-inline-block ">
					<div class="input-group">

						<div class="input-group-append">

							<a href="{{ path('app_campagne_index') }}" class="btn btn-primary  ">Retour a la page d'accueil</a>


						</div>
					</div>
				</form>
				<!-- Topbar Navbar -->
				<ul class="navbar-nav ml-auto">


					<!-- Nav Item - Alerts -->


					<!-- Nav Item - Messages -->
						<li class="nav-item dropdown no-arrow mx-1"> <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-envelope fa-fw"></i>
							<!-- Counter - Messages -->
							<span class="badge badge-danger badge-counter">7</span>
						</a>
						<!-- Dropdown - Messages -->
						<div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
							<h6 class="dropdown-header">
								Message Center
							</h6>
							<a class="dropdown-item d-flex align-items-center" href="#">
								<div class="dropdown-list-image mr-3">
									<img class="rounded-circle" src="img/undraw_profile_1.svg" alt="...">
									<div class="status-indicator bg-success"></div>
								</div>
								<div class="font-weight-bold">
									<div class="text-truncate">Hi there! I am wondering if you can help me with a
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										                                            problem I've been having.</div>
									<div class="small text-gray-500">Emily Fowler · 58m</div>
								</div>
							</a>
							<a class="dropdown-item d-flex align-items-center" href="#">
								<div class="dropdown-list-image mr-3">
									<img class="rounded-circle" src="img/undraw_profile_2.svg" alt="...">
									<div class="status-indicator"></div>
								</div>
								<div>
									<div class="text-truncate">I have the photos that you ordered last month, how
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										                                            would you like them sent to you?</div>
									<div class="small text-gray-500">Jae Chun · 1d</div>
								</div>
							</a>
							<a class="dropdown-item d-flex align-items-center" href="#">
								<div class="dropdown-list-image mr-3">
									<img class="rounded-circle" src="img/undraw_profile_3.svg" alt="...">
									<div class="status-indicator bg-warning"></div>
								</div>
								<div>
									<div class="text-truncate">Last month's report looks great, I am very happy with
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										                                            the progress so far, keep up the good work!</div>
									<div class="small text-gray-500">Morgan Alvarez · 2d</div>
								</div>
							</a>
							<a class="dropdown-item d-flex align-items-center" href="#">
								<div class="dropdown-list-image mr-3">
									<img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="...">
									<div class="status-indicator bg-success"></div>
								</div>
								<div>
									<div class="text-truncate">Am I a good boy? The reason I ask is because someone
																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																																										                                            told me that people say this to all dogs, even if they aren't good...</div>
									<div class="small text-gray-500">Chicken the Dog · 2w</div>
								</div>
							</a>
							<a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
						</div>
					</li>

					<div class="topbar-divider d-none d-sm-block"></div>

					<!-- Nav Item - User Information -->
					<li class="nav-item dropdown no-arrow">
						<a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
							<img class="img-profile rounded-circle" src="img/undraw_profile.svg">
						</a>
						<!-- Dropdown - User Information -->
						<div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
							<a class="dropdown-item" href="#">
								<i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
								Profile
							</a>
							<a class="dropdown-item" href="#">
								<i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
								Settings
							</a>
							<a class="dropdown-item" href="#">
								<i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
								Activity Log
							</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
								<i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
								Logout
							</a>
						</div>
					</li>

				</ul>

			</nav>
			<div class="container-fluid  ">


				<h1 class="text-center">Nouveau Campagne</h1>

				{{ include('campagne/_form.html.twig') }}
				{# 
																				<a href="{{ path('app_campagne_index') }}">back to list</a> #}

			</div>
		{% endblock %}
		<!-- MDB -->
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.1.0/mdb.min.js"></script>
	</body>
</html>

templates/campagne/show.html.twig
{% extends 'base.html copy.twig' %}

{% block title %}Campagne
{% endblock %}

{% block body %}
	<h1>Campagne</h1>

	<table class="table">
		<tbody>
			<tr>
				<th>Id</th>
				<td>{{ campagne.id }}</td>
			</tr>
			<tr>
				<th>Libelle</th>
				<td>{{ campagne.libelle }}</td>
			</tr>
			<tr>
				<th>Date_debut</th>
				<td>{{ campagne.dateDebut ? campagne.dateDebut|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Date_fin</th>
				<td>{{ campagne.dateFin ? campagne.dateFin|date('Y-m-d') : '' }}</td>
			</tr>
			<tr>
				<th>Type</th>
				<td>{{ campagne.type }}</td>
			</tr>
			<tr>
				<th>Description</th>
				<td>{{ campagne.description }}</td>
			</tr>
		</tbody>
	</table>

	<a href="{{ path('app_campagne_index') }}">back to list</a>

	<a href="{{ path('app_campagne_edit', {'id': campagne.id}) }}">edit</a>

	{{ include('campagne/_delete_form.html.twig') }}
{% endblock %}